### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by reidjoshua** [YULIANGMAX/FuckingInternetTile#1]
-copying zip to temp directory 
!Unzip error

**Comment by YULIANGMAX** [comment]
> 

？？？

**Comment by reidjoshua** [comment]
> > 
> 
> ？？？

That's the log trying to install from magisk

**Comment by YULIANGMAX** [comment]
> > > 
> > 
> > 
> > ？？？
> 
> That's the log trying to install from magisk

1. Install Magisk 25.2
2. Install LSPosed 1.8.5
3. Install [Fucking.Internet.Tile.v1.2.apk](https://github.com/YULIANGMAX/FuckingInternetTile/releases/download/1.2/Fucking.Internet.Tile.v1.2.apk)
